// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: internal.proto

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	internal.proto

It has these top-level messages:
	Dial
	User
*/
package internal

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Dial struct {
	ID      int64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID  int64   `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Name    string  `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Level   float64 `protobuf:"fixed64,4,opt,name=Level,proto3" json:"Level,omitempty"`
	ModTime int64   `protobuf:"varint,5,opt,name=ModTime,proto3" json:"ModTime,omitempty"`
}

func (m *Dial) Reset()                    { *m = Dial{} }
func (m *Dial) String() string            { return proto.CompactTextString(m) }
func (*Dial) ProtoMessage()               {}
func (*Dial) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{0} }

func (m *Dial) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Dial) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Dial) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Dial) GetLevel() float64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Dial) GetModTime() int64 {
	if m != nil {
		return m.ModTime
	}
	return 0
}

type User struct {
	ID       int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{1} }

func (m *User) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*Dial)(nil), "internal.Dial")
	proto.RegisterType((*User)(nil), "internal.User")
}

func init() { proto.RegisterFile("internal.proto", fileDescriptorInternal) }

var fileDescriptorInternal = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x8a,
	0xb8, 0x58, 0x5c, 0x32, 0x13, 0x73, 0x84, 0xf8, 0xb8, 0x98, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x98, 0x83, 0x98, 0x3c, 0x5d, 0x84, 0xc4, 0xb8, 0xd8, 0x42, 0x8b, 0x53, 0x8b, 0x3c, 0x5d,
	0x24, 0x98, 0xc0, 0x62, 0x50, 0x9e, 0x90, 0x10, 0x17, 0x8b, 0x5f, 0x62, 0x6e, 0xaa, 0x04, 0xb3,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d, 0x24, 0xc2, 0xc5, 0xea, 0x93, 0x5a, 0x96, 0x9a, 0x23,
	0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x18, 0x04, 0xe1, 0x08, 0x49, 0x70, 0xb1, 0xfb, 0xe6, 0xa7, 0x84,
	0x64, 0xe6, 0xa6, 0x4a, 0xb0, 0x82, 0x8d, 0x80, 0x71, 0x95, 0x8c, 0xb8, 0x58, 0x40, 0xa6, 0x61,
	0xd8, 0x29, 0xc5, 0xc5, 0x01, 0x12, 0xcf, 0x03, 0x99, 0xcf, 0x04, 0x36, 0x1f, 0xce, 0x4f, 0x62,
	0x03, 0x3b, 0xdc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x81, 0xd3, 0xa6, 0xca, 0x00, 0x00,
	0x00,
}
